import { Toaster } from 'sonner';
import { inter } from '~/assets/fonts';
import { Header } from '~/components/Header';
import '~/styles/globals.css';

export const metadata = {
  title: 'Attios CRM',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }]
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body>
        <Header />
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
